### ISSUE TITLE
Octopus Example - TLS not working

### ISSUE THREAD

**Issue by pho-enix** [bosch-io/iot-things-examples#13]
Great to see this easy to use example with the Bosch IoT Suite and real embedded HW :)

Unfortunately I noticed that the example is not working, because the certificate fingerprint is outdated:
`
/* SHA-1 fingerprint of the server certificate of the MQTT broker, UPPERCASE and spacing */
#define MQTT_SERVER_FINGERPRINT "7E 8E 7E FF 65 3E C0 02 88 F4 43 AE C5 FE E0 ED 89 C6 E2 06"
`
The certificate fingerprint is:
`65 04 DC 0E 76 74 C7 FE 40 74 CE 79 04 16 6F 13 C4 0B 1D AD`

However it looks like they are using Let's Encrypt certs with only three months until they expire. Wouldn't it be better to validate the certificate against a CA and be less dependent on the cycles they use to rotate the certs?

**Comment by geglock** [comment]
I agree, but we would need help to do this.

The example uses the "WifiClientSecure" Arduino library and uses the "verify(fingerprint, domain") method. There is an additional method "verifyCertChain(domain)" but this probably has to know about the root ca.

Could you provide a patch/pull request showing what has to be done?

**Comment by pho-enix** [comment]
Thanks for your reply.

I hope I will find some spare time to have a look on this

**Comment by Yannic92** [comment]
Solved by #14
