### ISSUE TITLE
Can't establish secure connection to IoT Hub from Octopus-Things example

### ISSUE THREAD

**Issue by cgrotz** [bosch-io/iot-things-examples#17]
I tried to compile and execute the example today. After some debugging, it seems that the fingerprint for the Bosch IoT Hub MQTT Endpoint is wrong. (Wasn't this just changed this week?)

**Comment by zubairhamed** [comment]
It should be the same i think. What was changed was the one for AMQP where you'd use as a Hub consumer

**Comment by cgrotz** [comment]
Maybe I got confused, I downloaded the cert and it says let's encrypt. But maybe this was already switched to let's encrypt earlier.
```
Server certificate
subject=/CN=mqtt.bosch-iot-hub.com
issuer=/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
```

Does it work for you? It fails for me, when calling verifyCertChain with the message `Failed to verify certificate`. I'm not even at the login procedure yet. :-(

**Comment by dguggemos** [comment]
The certificate for the MQTT endpoint changed about 2 months ago, we'll check if the current certificate is up to date.

**Comment by Yannic92** [comment]
Validation has changed. Fingerprint is no longer hard coded. Did you pull the latest version of the example?
