### ISSUE TITLE
Octopus-Things example: Set TLS certificate before establish the connection to the MQTT broker

### ISSUE THREAD

**Issue by leischt** [bosch-io/iot-things-examples#26]
Thanks for the easy to use example, to connect the Octopus prototype board to the Bosch IoT Suite.

While playing around with this example I had to change the order to of the "wiFiClient.connect" and "wiFiClient.setCACert" calls at "connect" method of the"boschIotHub" class to establish a secure connection. So that the certificate is available before the connect call takes place.

It would be great if you could fix this to make the example work out of the box ;)

**Comment by Yannic92** [comment]
Feel free to provide such fixes as PR. We happily review and merge them :)

**Comment by Yannic92** [comment]
Although I could not reproduce the error you described on my octopus another colleague described the same behaviour. I fixed this in: deea94567291c029c61abd608d20408791b7ea8d
