### ISSUE TITLE
http-forwarder adds an empty key to payload json when path of event is "/"

### ISSUE THREAD

**Issue by Yannic92** [bosch-io/iot-things-examples#34]
When http-forwarder receives an event with a path that is equal to "/" this results in a JSON having an empty key on top level.

**Comment by ffendt** [comment]
https://github.com/bsinno/iot-things-examples/blob/master/http-forwarder/src/service/helpers.ts#L133
will need a different handling for the root path ('/')

**Comment by ghandim** [comment]
This is now part or Bosch IoT Things. Please have a look at https://docs.bosch-iot-suite.com/things/getting-started/booking/manage-y-connection/.
