### ISSUE TITLE
Tested new Arduino libraries successfully 

### ISSUE THREAD

**Issue by stefferber** [bosch-io/iot-things-examples#56]
Test on Mac 10.15.4 (19E287) and Arduino 1.8.12 following new versions work fine:
   1. [Adafruit Unified Sensor Library](https://github.com/adafruit/Adafruit_Sensor) (tested with 1.1.2)
   2. [Adafruit BME680 library](https://github.com/adafruit/Adafruit_BME680) (tested with 1.0.7)
   3. [Adafruit BME280 library](https://github.com/adafruit/Adafruit_BME280) (tested with 2.0.1)
   4. [Adafruit BNO055 library](https://github.com/adafruit/Adafruit_BNO055) (tested with 1.1.6 | 1.1.10 | 1.1.11)
   5. [Adafruit NeoPixel library](https://github.com/adafruit/Adafruit_NeoPixel) (tested with 1.1.7 | 1.3.5)
   6. [PubSubClient library](https://github.com/knolleary/pubsubclient) (tested with 2.7.0)
   7. [ArduinoJson](https://github.com/bblanchon/ArduinoJson) (tested with 5.13.4 | 5.13.5 does not work with 6.x.y) see issue #55 
   8. [ESP8266-Ping](https://github.com/dancol90/ESP8266Ping) (tested with 2.0.1)

and
 ESP8266 Platform to the IDE, see [ESP8266 Arduino Platform](https://github.com/esp8266/Arduino) (tested with 2.4.1 | 2.6.3)

**Comment by ghandim** [comment]
See #55.
