### ISSUE TITLE
octopus-firmware switch_led|setColor not working

### ISSUE THREAD

**Issue by thiloboehm** [bosch-io/iot-things-examples#58]
I followed the tutorial [step 4](https://docs.bosch-iot-suite.com/asset-communication/Step-4---Remote-control-your-Octopus-device.html) and tried to change the color of the led on my octopus board.

The current code only switches both led's off:

https://github.com/bosch-io/iot-things-examples/blob/7143f78e3872677445ea192845f8e50f7d451636/octopus-firmware/octopus-hub/octopus-hub.ino#L73-L76

If I change the lines 73-76 from `char` to `long` everything works as expected.

**Comment by ghandim** [comment]
@thiloboehm ~~I cannot reproduce this behavior with the current octopus-frontend and firmware. I am able to switch the LEDs of the board as expected.~~ Now I see the problem. I think the problem is this https://github.com/bosch-io/iot-things-examples/blob/7143f78e3872677445ea192845f8e50f7d451636/octopus-firmware/octopus-hub/octopus-hub.ino#L78 line. Can you please remove it and checkout if it then works as expected?

**Comment by thiloboehm** [comment]
@ghandim For me this just changes that only LED0 is switched off.
For me it looks more like all char values are empty and that's why the LEDs gets switched off.
I use all the latest libraries.

**Comment by ghandim** [comment]
@thiloboehm Sorry to hear that. But I can switch the color of both (or one) LED several times as expected with the available frontend and with no other modification of the firmware. Can you give me some more details?

**Comment by thiloboehm** [comment]
@ghandim Which details would be helpful?

My Octopus is pretty new. Ordered end of May 2020. 

These are my libs:
1. [Adafruit Unified Sensor Library](https://github.com/adafruit/Adafruit_Sensor) (tested with 1.1.3)
2. [Adafruit BME680 library](https://github.com/adafruit/Adafruit_BME680) (tested with 1.1.0)
3. [Adafruit BME280 library](https://github.com/adafruit/Adafruit_BME280) (tested with 2.0.2)
4. [Adafruit BNO055 library](https://github.com/adafruit/Adafruit_BNO055) (tested with 1.3.0)
5. [Adafruit NeoPixel library](https://github.com/adafruit/Adafruit_NeoPixel) (tested with 1.5.0)
6. [PubSubClient library](https://github.com/knolleary/pubsubclient) (tested with 2.8.0)
7. [ArduinoJson](https://github.com/bblanchon/ArduinoJson) (tested with 6.15.2)
8. [ESP8266-Ping](https://github.com/dancol90/ESP8266Ping) (tested with 2.0.1)

This is the log from Arduino Upload:
```
[Starting] Upload sketch - octopus-hub/octopus-hub.ino
[Warning] Output path is not specified. Unable to reuse previously compiled files. Upload could be slow. See README.
Loading configuration...
Initializing packages...
Preparing boards...
Verifying...
Executable segment sizes:
IROM   : 391348          - code in flash         (default or ICACHE_FLASH_ATTR) 
IRAM   : 28456   / 32768 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...) 
DATA   : 1476  )         - initialized variables (global, static) in RAM/HEAP 
RODATA : 4288  ) / 81920 - constants             (global, static) in RAM/HEAP 
BSS    : 26272 )         - zeroed variables      (global, static) in RAM/HEAP 
Sketch uses 425568 bytes (40%) of program storage space. Maximum is 1044464 bytes.
Global variables use 32036 bytes (39%) of dynamic memory, leaving 49884 bytes for local variables. Maximum is 81920 bytes.
Uploading...
esptool.py v2.8
Serial port /dev/tty.SLAB_USBtoUART
Connecting....
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: xx:xx:xx:xx:xx:xx
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 4MB
Compressed 429728 bytes to 314338...

Writing at 0x00000000... (5 %)
Writing at 0x00004000... (10 %)
Writing at 0x00008000... (15 %)
Writing at 0x0000c000... (20 %)
Writing at 0x00010000... (25 %)
Writing at 0x00014000... (30 %)
Writing at 0x00018000... (35 %)
Writing at 0x0001c000... (40 %)
Writing at 0x00020000... (45 %)
Writing at 0x00024000... (50 %)
Writing at 0x00028000... (55 %)
Writing at 0x0002c000... (60 %)
Writing at 0x00030000... (65 %)
Writing at 0x00034000... (70 %)
Writing at 0x00038000... (75 %)
Writing at 0x0003c000... (80 %)
Writing at 0x00040000... (85 %)
Writing at 0x00044000... (90 %)
Writing at 0x00048000... (95 %)
Writing at 0x0004c000... (100 %)
Wrote 429728 bytes (314338 compressed) at 0x00000000 in 27.6 seconds (effective 124.5 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
[Done] Uploaded the sketch: octopus-hub/octopus-hub.ino
```

This is the serial output after sending the switch_led command:
```
[Bosch IoT Hub]     Received command on topic: command///req/00fmessage-examplereplies/switch_led
switch_led
[Bosch IoT Hub]     Publishing on topic: command///res/00fmessage-examplereplies/200
[Bosch IoT Hub]     {"topic":"com.xxx.xxx.xxx/octopus1/things/live/messages/switch_led","headers":{"sec-fetch-mode":"cors","referer":"http://localhost:8080/","sec-fetch-site":"cross-site","accept-language":"de-DE, de;q=0.9, en-US;q=0.8, en;q=0.7","correlation-id":"message-example","origin":"http://localhost:8080","x-things-parameter-order":"[\"r\",\"g\",\"b\",\"w\"]","x-correlation-id":"message-example","version":2,"timeout":"10","accept":"application/json, text/plain, */*","ditto-originator":"iot-suite:/service-instance.xxxx-xxxx-xxxx-xxxx-xxxx.iot-things@xxxx-xxxx-xxxx-xxxx-xxxx","content-type":"application/json","accept-encoding":"gzip, deflate, br","timestamp":"2020-07-02T22:15:47.452407998+02:00","sec-fetch-dest":"empty"},"path":"/inbox/messages/switch_led","value":"\"Command 'switch_led' executed\"","status":200}
```

This is the message:
```json
{
    "topic": "com.xxx.xxx.xxx/octopus1/things/live/messages/switch_led",
    "headers": {
        "sec-fetch-mode": "cors",
        "referer": "http://localhost:8080/",
        "sec-fetch-site": "cross-site",
        "accept-language": "de-DE, de;q=0.9, en-US;q=0.8, en;q=0.7",
        "correlation-id": "message-example",
        "origin": "http://localhost:8080",
        "x-things-parameter-order": "[\"r\",\"g\",\"b\",\"w\"]",
        "x-correlation-id": "message-example",
        "version": 2,
        "timeout": "10",
        "accept": "application/json, text/plain, */*",
        "ditto-originator": "iot-suite:/service-instance.xxxx-xxxx-xxxx-xxxx-xxxx.iot-things@xxxx-xxxx-xxxx-xxxx-xxxx",
        "content-type": "application/json",
        "accept-encoding": "gzip, deflate, br",
        "timestamp": "2020-07-02T22:20:02.281130239+02:00",
        "sec-fetch-dest": "empty"
    },
    "path": "/inbox/messages/switch_led",
    "value": {
        "r": 128,
        "g": 0,
        "b": 0,
        "w": 0
    }
}
```

**Comment by ghandim** [comment]
@thiloboehm Can you please try it again with the versions mentioned in [README.md](https://github.com/bosch-io/iot-things-examples/blob/master/README.md)? Thx.
Install the following libraries (Sketch -> Include Library -> Manage Libraries)
* Adafruit BME680 (tested with 1.0.7)
* Adafruit BME280 (tested with 1.0.7)
* Adafruit BNO055 (tested with 1.1.6)
* Adafruit NeoPixel (tested with 1.1.7)
* Adafruit Unified Sensor (tested with 1.1.2)
* PubSubClient (tested with 2.7.0)
* ArduinoJson (tested with 6.15.2)
* ESP8266-ping (tested with 2.0.1)

**Comment by thiloboehm** [comment]
@ghandim I tried it with the versions from the [README.md](https://github.com/bosch-io/iot-things-examples/blob/master/README.md).
My result is the same as I described in my first post.

**Comment by ghandim** [comment]
@thiloboehm Now I got it. There is a glitch in our documentation. Please send the value in the message with surrounding "". Then it should work as expected, e.g. {"r": "10"}. Can you please check? Sorry for the inconvenience.

**Comment by ghandim** [comment]
@thiloboehm After some investigation and cross checking our documentation I implemented your proposal. Thanks for the hint.
