### ISSUE TITLE
plans about data persistence  

### ISSUE THREAD

**Issue by AndreiD** [bosch-io/iot-things-examples#6]
not an issue: 

Scenario: some sensors send data every x seconds.
Internet fails for 1 hour.
Data has to be kept in sync.

Do you have any plans to implement persistence... (like Firebase), or it's our the responsibility ?

**Comment by BennoSI** [comment]
Hi Dan, 

Do you mean client sided persistence? 
At the moment we only provide persistence in our cloud backend. 

Depending from your scenario, you could for example always hold the last sensor value within a cache and when the connection was established again you could send this value with the things client.

regards,
Benno

**Comment by AndreiD** [comment]
all right.
