### ISSUE TITLE
Provide example of how to use CompletionStages based API

### ISSUE THREAD

**Issue by thjaeckle** [bosch-io/iot-things-examples#7]
Currently we have rather simple Things Client examples which use blocking `.get()` with a specified timeout a lot.
Better would be examples which use `CompletionStage`s which are orchestrated together to form a more "what is happening" instead of a "how is it happening" programming style.

**Comment by ghandim** [comment]
Client and examples moved to https://github.com/eclipse/ditto-examples/tree/master/java-client.
